### ISSUE TITLE
MOBILE: Add Liquidity button alignment/selection

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#124]
Clean up the mobile / compressed button view:
- Mobile resizes these fields, and the highlight when selected populates the blue circles. Can we centre align these, so they're width and height aligned with each other even if text is wrapping, as well as ensuring the backgrounds are fully used by the light blue 'selected' highlight?
- can be reproduced on desktop by compressing the page vertically

![image](https://user-images.githubusercontent.com/72741063/95988234-54678e00-0e74-11eb-8ba2-9cbd2f23aa2e.png)

**Comment by f1ntch** [comment]
Fixed  @SP-Nate 

![image](https://user-images.githubusercontent.com/12197739/96035620-94724500-0e63-11eb-934c-6267a4bcc3c2.png)


![image](https://user-images.githubusercontent.com/12197739/96035839-e2874880-0e63-11eb-8e0b-f88120a2f9b9.png)

**Comment by f1ntch** [comment]
Also fixed an auto height on the cards standing next to each other.

![image](https://user-images.githubusercontent.com/12197739/96036784-3f373300-0e65-11eb-8f1d-6ec7cc808971.png)

**Comment by SamusElderg** [comment]
Good job!
