### ISSUE TITLE
SWAP & LIQUIDITY PAGES | Change 'back' button's theme and/or placement

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#126]
Can we try changing the theming of this button or maybe the placement? 
Something about it doesn't seem right 🤷 

![image](https://user-images.githubusercontent.com/26967164/96010011-eae77f80-0e73-11eb-8fb7-1b468db9203c.png)

**Comment by f1ntch** [comment]
Thoughts on the new position and styling?
@SamusElderg 


I personally prefer 1

**1**
![image](https://user-images.githubusercontent.com/12197739/96033600-91c22080-0e60-11eb-833c-4685884af618.png)

**2**
![image](https://user-images.githubusercontent.com/12197739/96033095-ee710b80-0e5f-11eb-8394-ab2b459ce3dc.png)

**3**
![image](https://user-images.githubusercontent.com/12197739/96033326-3abc4b80-0e60-11eb-9bba-bcd29e8473ae.png)

**Comment by SamusElderg** [comment]
#1 is perfect thanks!
