### ISSUE TITLE
SWAP PAGE | Add calculated 'price/rate' & add calculated 'slip'

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#127]
@f1ntch ill need your input on theming of this once i have added the other details 👍 

![image](https://user-images.githubusercontent.com/26967164/96010490-6b0de500-0e74-11eb-8e92-59b787bae1dd.png)

**Comment by f1ntch** [comment]
Will make a mockup so we can discuss the placing of the elements then I will code them. @SamusElderg

**Comment by SamusElderg** [comment]
Thanks 👍
