### ISSUE TITLE
POOL TABLE | Header text not visible in light/day mode

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#131]
In day-mode theme we can't see the table headers as we haven't set up table headers to use a secondary fontColor.

Ill leave this in your court @f1ntch to set up however you think is best to match the light-theme 👍 

![image](https://user-images.githubusercontent.com/26967164/96054897-471ec380-0eb5-11eb-9e2c-27f4b13d528d.png)

**Comment by f1ntch** [comment]
Fixed

![image](https://user-images.githubusercontent.com/12197739/96184942-75de7d80-0f39-11eb-9d60-bb4f435d92d6.png)
