### ISSUE TITLE
MOBILE RESPONSIVE (iPhone 5) - POOLS TABLE | Fix buttons

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#136]
Fix buttons in pools table (on thin phones like i5 / SE)

![image](https://user-images.githubusercontent.com/26967164/96083353-9a156c80-0eef-11eb-947f-c13d6c3f5619.png)

**Comment by f1ntch** [comment]
Fixed


![image](https://user-images.githubusercontent.com/12197739/96183547-4dee1a80-0f37-11eb-8935-2462d8fde77a.png)

**Comment by SamusElderg** [comment]
Thanks buddy! 👍

**Comment by SamusElderg** [comment]
Awesome! Thanks!

**Comment by SamusElderg** [comment]
Hey buddy did you push this to the branch? Still looks like this when i run it on your branch:

![image](https://user-images.githubusercontent.com/26967164/96194287-a398e600-0f7c-11eb-8825-f398e163a0fd.png)

**Comment by SamusElderg** [comment]
It appears to break when you change between dark/light mode!
Ill check and fix if i can quickly figure it out 👍

**Comment by SamusElderg** [comment]
Sorted! Just moved style.css code to the end of the _button.scss (was a css priotity issue)

Change a few things too so that it does it all the way up to 390px (this was where the breaking started)
