### ISSUE TITLE
MOBILE RESPONSIVE (iPhone 5) - SWAP + LIQUIDITY PAGES | Fix layout on small mobiles

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#137]
On small mobile phones you have to scroll across to see details in the TRADE PANEL 

Lets make this better on mobile

![image](https://user-images.githubusercontent.com/26967164/96083558-f5dff580-0eef-11eb-955e-700fec0721c6.png)

**Comment by f1ntch** [comment]
Fixed

Added the elements that were causing a scroll on small mobile devices into the row.
![image](https://user-images.githubusercontent.com/12197739/96632260-bf531200-1317-11eb-88f3-526ceab08cf7.png)

**Comment by SamusElderg** [comment]
Love it thanks buddy!
