### ISSUE TITLE
Light switch gradient

### ISSUE THREAD

**Issue by f1ntch** [spartan-protocol/spartanpools-dapp#147]
The the colors of the gradient did not fit in with the rest of the theme and felt a little weird also changed the colors and the icon to white![image](https://user-images.githubusercontent.com/12197739/96187029-98be6100-0f3c-11eb-9238-2d8374193c19.png)

**Comment by f1ntch** [comment]
Will style it some more

**Comment by SamusElderg** [comment]
Thanks 👍 knew you would come through and fix this haha you have a much better eye for these things!
