### ISSUE TITLE
BREADCRUMBS | Fix - Links Are Wrong

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#149]
Let's fix the breadcrumbs component so it links to the correct links as expected

**Comment by f1ntch** [comment]
Fixed 
Breadcrumb link redirects as expected now.
![image](https://user-images.githubusercontent.com/12197739/96628286-52894900-1312-11eb-95af-1ef6183b1b27.png)

**Comment by SamusElderg** [comment]
Awesome! Good job!
