### ISSUE TITLE
DATA REFRESH | Changing web3 wallet reloads walletData[ALL] & sharesData[ALL]

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#174]
When a user has more than one BSC Wallet address, changing the wallet in Metamask will result in SP remaining locked to the prior wallet, until a hard refresh is performed. Perform a regular check to identify whether the current 'wallet' has changed, and force a hard refresh/re-calculation when in Earn and Pools

**Comment by SamusElderg** [comment]
@SamusElderg look at this tomorrow
