### ISSUE TITLE
UX: Maintain view when transitioning between dApps

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#177]
Currently, should a user select 'Load More' on Earn or Pool, and then navigate to the other dApp, upon returning to the initial dApp, their view is truncated. If the additional LP or LP Stake elements have been loaded, continue to use them rather than forcing a user to re-load unnecessarily

**Comment by SamusElderg** [comment]
@SP-Nate can you check and confirm this is solved with recent updates?
I don't think it applies anymore but not 100% sure what you are describing :P

**Comment by SamusElderg** [comment]
@SP-Nate im marking this as closed but feel free to re-open with a screenshot or similar if it is not solved
