### ISSUE TITLE
UX-UI: Resolve outstanding Percentage Swap Button issue

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#182]
On the Swap page, the buttons for 25%, 50%, 75% and All are not functioning as efficiently as possible, with several issues:

By default, the 'Total' is populated with a rounded amount of an asset, which will trigger a contract error (attempting to swap more token than exists in the wallet). 
- Recommend enhancing this to automatically calculate the max value to 'N' decimal places, however round DOWN the display to two decimal places. This will allow users to swap 'all' of a token and not have any leftover dust, but will visually be easier to read.

Inserting a manual Total will render the buttons obsolete, as they are not linked to the prior 'Total' SPARTA in the wallet. Recommend adding a 'Clear existing Total' step to the percentage buttons, to allow it to better adjust the amount presented to an end user.

**Comment by SamusElderg** [comment]
closed with #306
