### ISSUE TITLE
UI - Swap screen

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#183]
Enhance Swap screen with the below:
- add 2 decimal places to Fees 
- add 2 decimal places to Est. Slip

**Comment by SamusElderg** [comment]
We can use formatAllUnits() which will change the decimals to suit the asset price

Pretty sure it will be suitable for the est. slip too 

Wait for new UI or fix this now? @SP-Nate what do you think?
