### ISSUE TITLE
After Metamask login, Wallet has a cross next to it - needs to be clicked on for tick to appear

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#190]
Observation: In the past 2 days, after logging into Metamask (on a desktop), there has been a cross next to the wallet icon in the top right hand corner, instead of a tick. 
I have found it necessary to left click on the wallet symbol for the wallet to load and token data, harvestable Sparta quantity etc. to become visible on the pools / earn pages.

**Comment by SamusElderg** [comment]
closed with #205
