### ISSUE TITLE
WALLET REFRESH | Harvesting does not trigger user data refresh

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#191]
Observation: After harvesting Sparta from emissions, upon visiting the Pools page to add the harvested Sparta into a pool, I found that the wallet data had not been refreshed to include the harvested Sparta quantity.
I found it necessary to refresh the browser in order for the Pools page to include the harvested Sparta in the available Sparta quantity for pooling.

**Comment by SamusElderg** [comment]
fixed with #219
