### ISSUE TITLE
Request to add "Max Symmetrical" pool button / "Force Symmetrical pooling" tick box

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#192]
Request: 
Would it be possible to have either
(1) a "max symmetrical" add button, in addition to the 25% / 50% / 75% / 100% options? 
and/or
(2) a "force symmetrical" option?
Either way, if the pooling page could determine the lower $ value of the two tokens available in the wallet for pooling, and then set 25% / 50% / 75% / 100% according to the lower value?
This would then prevent inadvertent asymetrical staking by those users not yet familiar with the concept or consequences.

**Comment by SamusElderg** [comment]
#2 is now sorted via the new UI a week or two ago 👍 

#1 is no longer relevant, same dealio; solved with recent changes

Thanks!
