### ISSUE TITLE
Refresh wallet data after pooling, to see updated LP token quantity

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#194]
Observation: after adding Sparta + other token to a pool, the wallet data was not updated.
As a result, when clicking on the wallet symbol, the LP token quantity had not been updated / refreshed
I found it necessary to refresh the browser page for the wallet data to reload to see the updated LP quantity.

**Comment by SamusElderg** [comment]
New issue created #222
