### ISSUE TITLE
HEADER | Fix vertical align (only on small devices)

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#203]
The left and right half of the header misaligns on some screen sizes

![IMG_20201029_072252~2.jpg](https://user-images.githubusercontent.com/26967164/97507281-d056ef80-19b7-11eb-9a73-09992c5ea661.jpg)

**Comment by f1ntch** [comment]
fixed
![image](https://user-images.githubusercontent.com/12197739/99435868-07faec80-2911-11eb-9eed-15b5dd46aec8.png)
