### ISSUE TITLE
Request: Have connect/disconnect slider next to wallet (instead of cross or tick)

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#204]
Observation: It is not immediately obvious that one needs to click on the wallet to change status from cross to tick, even after the Metamask login. Perhaps a slider from Red (disconnected) to Green (connected) would be a better visual guide / prompter?

**Comment by SamusElderg** [comment]
Good idea 👍
The plan is to have it automated but regardless green/red switch is better than the icon!

Or maybe a traffic light that is green when connected, orange when connecting and red when disconnected? What do you think?

**Comment by SamusElderg** [comment]
Or the switch as you say but with red/orange/green for various states
