### ISSUE TITLE
EARN PAGE | Fix the 'pools' stat, it reports 1 higher than it should

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#208]
Also change the 'pool' 'pools' condition proceeding 'are' word to be conditional too

And make it so it only says 'pool' when === 1

Make another condition for 0 pools where the whole sentence is different 

![IMG_20201030_153540.jpg](https://user-images.githubusercontent.com/26967164/97672924-dc30d780-1ac5-11eb-9129-e0d7cd96e504.jpg)

**Comment by SP-Nate** [comment]
Update this insight to reference pools where LP tokens staked > 0, rather than approved pools

Add in separate message if LP staked pools = 0 - welcoming users to join the shield wall

**Comment by SamusElderg** [comment]
Have removed it for now 👍
