### ISSUE TITLE
Adding BNB + SPARTA = exception

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#23]
If you add BNB + SPARTA it throws exception.
BNB on it's own is fine though

Will get some BUSD tomorrow and test if that throws same

![image](https://user-images.githubusercontent.com/26967164/94367634-91145500-0112-11eb-936d-eed5db4b431e.png)

Also happens on swap page for BUSD->SPARTA:
![IMG_20200928_065316.jpg](https://user-images.githubusercontent.com/26967164/94377883-6dbfc900-0157-11eb-8e04-d91d0ddb0cb2.jpg)

I suspect it's a number formatting issue

**Comment by SamusElderg** [comment]
Check Ether.Utils

**Comment by spartan-admin** [comment]
wasn't able to replicate, tho suspect BUSD wasn't approved on the contract
