### ISSUE TITLE
Need to scroll up and down in pools page to see all page content

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#235]
On the pools page, I have observed it is not possible to see the Add to Pool button without scrolling down.
Alternatively cannot see available balances when can see the Add to Pool button.

On my laptop screen, 1366x768, hen I scroll down to the "Add to Pool" area and adjust quantity to pool, I can no longer see the available quantities section above, so I need to scroll up and down to check each time I want to adjust the quantity to pool again.

On my extended display, 1920x1080, if I am at the top of the page, I cannot see the "Add to Pool" button.

Would it be possible to reduce the row spacer pixel size, so that everything becomes visible?

Windows 10, Chrome 86.0.4240.183 (official build) (64-bit)

**Comment by SamusElderg** [comment]
closed with #315
