### ISSUE TITLE
POOL PANE SIDE | Rebuild UI similar to new swap page layout

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#250]
lets look at re-activating @f1ntch 's bright progress bars with relevant variables plugged in

for instance we can grab the price data from 24hrs ago (coingecko?) and use that as the base of the chart and current price to the right to show price variance visually

do something similar for the other stats

Before (Desktop):
![image](https://user-images.githubusercontent.com/26967164/99936594-740ca300-2d9e-11eb-854b-516de2b948c5.png)

Before (Mobile):
![image](https://user-images.githubusercontent.com/26967164/99952461-ac21df00-2dba-11eb-9341-b45cbe50ec0e.png)

**Comment by f1ntch** [comment]
Will look up coingecko API's and look into the possibilities!

**Comment by SamusElderg** [comment]
> Will look up coingecko API's and look into the possibilities!

Awesome! Let me know if you have any questions or ideas you want to bounce of us 👍
