### ISSUE TITLE
Sell non-Sparta quantity not updating with slider, after manually over-riding quantity

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#257]
Have observed just now that 
-initially the slider will update both non-Sparta quantity being sold, and the Sparta quantity being bought
-after manually over-riding the non-Sparta quantity being sold (e.g. BNB), using the slider afterwards no longer updates the non-Sparta quantity being sold.
For example, if 0.1 BNB is manually entered to be sold, then the value remains at 0.01 when use of the slider is resumed.

**Comment by SamusElderg** [comment]
Ouch! Thanks for picking that up @LinksterMJ ! Lucky we set the default at such a low %

Will fix today 👍

**Comment by SamusElderg** [comment]
Turns out this is just the input that (visually) doesnt change 👍 
All the other variables (input/output rate etc) actually change properly so this is the same as the other issues on github to do with the percent buttons and/or clearing the input on % change

**Comment by SamusElderg** [comment]
closed with #306
