### ISSUE TITLE
Long decimals hidden overflow - Tooltip for full value

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#28]
Make sure values that overflow out of their div don't break the UI

Instead, have a tooltip hover for each so that users can see the full value by tapping (mobile) or hovering (desktop)

**Comment by f1ntch** [comment]
I will look into this when i get home.

**Comment by SamusElderg** [comment]
> I will look into this when i get home.

Awesome thanks!

**Comment by f1ntch** [comment]
![tooltip](https://user-images.githubusercontent.com/12197739/94477584-67bafe00-01d2-11eb-92e8-9c71266b7172.png)

Can you indicate for which values ​​I should implement those tooltips?
And to how much the displayed value should be rounded / truncated?

Another question
Which tools do you use to simulate dummy data for meta mask on the localhost?

**Comment by f1ntch** [comment]
![tooltip](https://user-images.githubusercontent.com/12197739/94479073-8621f900-01d4-11eb-803d-3bd808df1706.png)

Can you indicate for which values ​​I should implement those tooltips? (where the long decimals occur)
And to how much the displayed value should be rounded / truncated?

**Comment by SamusElderg** [comment]
### POOLS PAGE
- Make sure ',' (comma) thousand indicator applies to all

**PRICE:**
- No rounding; leave as is for now.

**DEPTH:**
- Round to $ (no cents)
- No tooltip

**VOLUME**
- Round to $ (no cents)
- No tooltip

**REVENUE**
- Round to $ (no cents)
- No tooltip

### `<PoolPaneSide>` in `common.js`
- Make sure ',' (comma) thousand indicator applies to all

**DEPTH:**
- Round to 2 decimals
- No tooltip

**VOLUME**
- Round to $ (no cents)
- No tooltip

**PRICE:**
- No rounding; leave as is for now.

**FEES:**
- Round to $ (no cents)
- No tooltip

**APY**
- round to 2 decimals
- Tooltip full number

**Comment by SamusElderg** [comment]
closed by #63
