### ISSUE TITLE
BOND + EARN: Integration of these two interfaces

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#282]
Enhance Earn to allow a user to either:

A) Access 'Bond' via a button, if their wallet has no existing vested LP Tokens to claim
B) Claim vested LP Tokens natively from the Earn screen, with relevant insights, if user has vested LP Tokens pending or remaining.

Users will then be able to access Pools directly for Swap or Liquidity Provision (as well as Bond), or able to immediately go to Earn for harvesting of Yield or vested LP Tokens, as well as Lock or Unlock for more yield.

**Comment by SamusElderg** [comment]
Thanks @SP-Nate 👌

**Comment by SamusElderg** [comment]
Redundant now, however, we will look at integrating the functionality of bond and DAO etc with the new shares/overview page 👍
