### ISSUE TITLE
Precision on token is off

### ISSUE THREAD

**Issue by jchung00** [spartan-protocol/spartanpools-dapp#283]
GIV token has 8 decimals of precision. It seems like the UI thinks that the token has 18 decimals of precision. 
![photo_2020-11-19_21-43-29](https://user-images.githubusercontent.com/19266519/99751491-47ac0a80-2ab0-11eb-8420-a4a5630521f7.jpg)

**Comment by SamusElderg** [comment]
Thanks! Will add a check in the UI for getting the dec precision of each token and plugging that into the format functions 👍
