### ISSUE TITLE
SWAP | Disable buy/sell button if input > balance

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#288]
Observation: I was swapping SPARTA input for BNB ouput, and entered an amount of SPARTA manually that was greater than my available balance of SPARTA. The UI did not detect this, and Metamask tried to process, but failed due to available balance being exceeded.
Suggestion: check that manually entered amount of input token does not exceed available balance before passing to Metamask, and prevent swap, prompting user to enter an amount that does not exceed the available balance of input token.

**Comment by SP-Nate** [comment]
Note: 
- Please continue to allow users to manually enter a higher allocation of SPARTA or ASSET
- Perform an additional validation check when a user attempts to perform a swap by clicking <Buy Asset>

If Proposed Asset quantity > available Asset quantity, reject in UI and advise User

**Comment by SP-Nate** [comment]
Another point: In line with these changes, if a user enters the SWAP screen but does not have any of that specific asset, it would be a good idea to still display the full SWAP interface.

![image](https://user-images.githubusercontent.com/72741063/99919966-b4efc200-2d74-11eb-8f9d-086a8c577912.png)

![image](https://user-images.githubusercontent.com/72741063/99919974-c042ed80-2d74-11eb-939e-cd78d006d278.png)

Continue to show the full detailed view (image one above) however disable the ability to click the 'Sell Asset' button, and change the button label to something like '0 ASSET available'
