### ISSUE TITLE
EARN Page - calculate and display APY

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#293]
Introduce a  visible APY in the Earn screen (take into consideration the proposed changes involved with ]https://github.com/spartan-protocol/spartanpools-dapp/issues/282)

Allow this to be visible to any user and calculated based solely on Yield, to avoid large spikes and troughs in individual Pools based on how users are staking and/or swapping,and call this out. 'APY (excl swap fees) etc.

We can address Pool-level APY details in the near future

**Comment by SamusElderg** [comment]
Redundant now, however, we will need to tackle APY in the other relevant areas of the DApp
