### ISSUE TITLE
Enhance ROUTER V2 to manage non-18 Decimal Tokens

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#345]
https://bscscan.com/tx/0x237c01ca1c80315da0a9424e2497a275620e1b040ab8746902e499650543d701

TxID shows the below:

20,000 SPARTA sent to Pool
998,835 GIV sent via Router to Wallet
0.000025 SPARTA dividends paid to pool

Slip = 2.717%

https://bscscan.com/tx/0x37e81854b1ef6af5fe2a118bd9c05e2fef4d9dbeab1e6347b5443ef38c4206be

TxID shows the below:

4,500 SPARTA sent to Pool
7.78 BNB sent via Router to Wallet
0.502292 SPARTA dividends paid to pool

Slip = 0.116%

Slip and therefore fees is much higher in the GIV Swap, however dividend injection is significantly lower in the GIV Pool. Please validate how Router V2 applied these dividends. Is this a potential GIV precision issue?

**Comment by SP-Nate** [comment]
Confirmed by @SamusElderg as being directly linked to non-standard token decimals

**Comment by SamusElderg** [comment]
This is for the contracts repo, have moved it there
