### ISSUE TITLE
WEB UX: Improvements 

### ISSUE THREAD

**Issue by KIC8462852-sol** [spartan-protocol/spartanpools-dapp#359]
Always show underlying contract addresses. 

## On home Page 
* Sparta price (inverse of Busd price) on home page. 
* Sparta supply 
* Sparta MCap (supply x price) 

## Contract addresses drop down in info
// list with a 1 sentence description  
* sparta
* dao
* utils
* router
* bond
* any major sparta contract

## Pools details 
// On both join and swap and bond
*Pool contract
*token contract

**Comment by SamusElderg** [comment]
:👍 thanks !

**Comment by SamusElderg** [comment]
![image](https://user-images.githubusercontent.com/26967164/103535217-549f8480-4ecb-11eb-8253-eca4bfe69bec.png)
