### ISSUE TITLE
LP Estimate for Asymmetric Pool includes SPARTA

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#361]
Initial load of 'Add Asset' page (asymmetrically) includes an estimate for LP Tokens. This estimate appears to include SPARTA and is therefore double the expected value (and probably also doesn't include slip)

**Added info for Dev reference:**

ONLY on initial load of the asymmetric component, upon change of slider/manual input it fixes. Proposed solution: clear the input on tab-change. Or input a minimum figure on tab change

**Comment by SamusElderg** [comment]
Thanks!
