### ISSUE TITLE
CONTRACTS MENU: Enhancements

### ISSUE THREAD

**Issue by SP-Nate** [spartan-protocol/spartanpools-dapp#394]
![image](https://user-images.githubusercontent.com/72741063/103958795-0e377780-51a2-11eb-9eb3-74ed3edf99cc.png)

Enhance this view to display the below details:

- Total Supply 
Volume as per SPARTA Contract
- Circulating Supply
Calculate the total number of SPARTA currently contained in one of the three below sources, and subtract from Total Supply
a) DAO
b) Bond V2
c) Bond V3
- Max Supply 
300,000,000 SPARTA
- Market Cap
Current CoinGecko Price x Circulating Supply

If possible, introduce an additional toggle or similar modifier allowing a user to switch between SPARTA that is _claimable but still part of Bond V2 or V3 Tokens_ as Included or Excluded from Circulating Supply (and therefore re-calculate Market Cap).

By default, consider all SPARTA locked into DAO+Bond Contracts as out of circulation.  It is not until these LP Tokens are claimed and accessible in a user-controlled wallet that they can be considered circulating.

**Comment by SamusElderg** [comment]
@SP-Nate this is great thanks bud! on it now!

**Comment by SamusElderg** [comment]
closed with #402
