### ISSUE TITLE
INPUTS | Reset inputs to 0% after txn

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#403]
**_Initial issue:_**
Entered my actual wallet quantity of Sparta to 18 decimals (several hundred)
Approved SPARTA spend --> button changed to Spend BNB, quantity of SPARTA in the input box still correct, but BNB quantity changed
Clicked on Spend BNB and processed - exactly 1/100th of the quantity of SPARTA in the input box was swapped for BNB
(so only a few Sparta was swapped for BNB)

**_Updated Issue:_**
- After txn/swap/approve etc the UI resets the input to 1%
- Let's change this to 0% so that the submit button disappears in case the user doesn't realise input has reset

**Comment by SamusElderg** [comment]
Thanks buddy!
Will hash out a UX flow plan for this as I agree; it isn't perfect!
