### ISSUE TITLE
Header & Footer - Socials Update - 

### ISSUE THREAD

**Issue by verifythestack** [spartan-protocol/spartanpools-dapp#415]
Following on from #412 | suggest that we add at least the link to the socials on there 

<img width="229" alt="Screen Shot 2021-01-16 at 6 24 12 pm" src="https://user-images.githubusercontent.com/75196497/104805981-29505a00-5828-11eb-95ce-636e63fbe0db.png">

**Comment by SamusElderg** [comment]
Perfect thanks 👍 
Will sort it this weekend!

**Comment by verifythestack** [comment]
Figured I should use GitHub to log stuff, sorry for not doing it on the last couple.

I will get better with the search for issue thing, and then also the log on there =D
