### ISSUE TITLE
Pools data won't load

### ISSUE THREAD

**Issue by grallc** [spartan-protocol/spartanpools-dapp#473]
Whenever I go on the DApp, no data is shown (cf. screenshot)
![image](https://user-images.githubusercontent.com/14354161/108497191-5e2e5180-72ab-11eb-8a85-53b8a60ba99b.png)

I do have these logs in my Browser's console
```
Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at c.decodeParameters (index.js:338)
    at N.f._decodeMethodReturn (index.js:572)
    at f.outputFormatter (index.js:935)
    at f.formatOutput (index.js:169)
    at s (index.js:653)
    at a (util.js:689)
    at p.run (browser.js:153)
    at d (browser.js:123)
```

**Comment by SamusElderg** [comment]
You need to connect metamask to BSC mainnet 👍 
Either that or you havent allowed your wallet to interact with the dapp yet

**Comment by SamusElderg** [comment]
Reach out if you want me to troubleshoot with you and get it connecting 👍

**Comment by grallc** [comment]
> You need to connect metamask to BSC mainnet 👍
> Either that or you havent allowed your wallet to interact with the dapp yet

Ok thanks :)
I guess it'd be an better UX to show a message telling this instead of just "NaN"

Also, it's quite weird, because when I go in incognito mode without the metamask extension, it doesn't show the buggy page I sent in my issue but this 
![image](https://user-images.githubusercontent.com/14354161/108511811-b0c63880-72c0-11eb-8283-8eebdd68a80b.png)

So Metamask probably makes the page buggy until being linked with the DApp :)

**Comment by SamusElderg** [comment]
Looks like two possible issues here, first issue is that you have metamask but maybe have not unlocked your wallet?
It detects metamask and a wallet and connects to its RPC but because you haven't allowed the website to interact with metamask or maybe just haven't unlocked your wallet, it isn't being allowed to use its RPC URL yet.

Potentially you are using 'Brave' browser and have not disabled shields also?

In incognito with no metamask, it uses the default RPC grabbed from within the app (hence why it worked)

**Comment by grallc** [comment]
> Looks like two possible issues here, first issue is that you have metamask but maybe have not unlocked your wallet?
> It detects metamask and a wallet and connects to its RPC but because you haven't allowed the website to interact with metamask or maybe just haven't unlocked your wallet, it isn't being allowed to use its RPC URL yet.
> 
> Potentially you are using 'Brave' browser and have not disabled shields also?
> 
> In incognito with no metamask, it uses the default RPC grabbed from within the app (hence why it worked)
Probably that

I'm actually not using Brave, just a "classic" Chrome

**Comment by SamusElderg** [comment]
Perfect, that rules out the shield then 👍

Will just be to do with having metamask but either not unlocking the wallet and/or maybe have not allowed the DApp to interact with your wallet yet 

If it's not that, let me know as that means you have some wierd fringe case
