### ISSUE TITLE
Metamask behaviour when last used Ethereum network (i.e. not BSC mainnet)

### ISSUE THREAD

**Issue by LinksterMJ** [spartan-protocol/spartanpools-dapp#491]
Issue / Improvement opportunity (depends upon Metamask behaviour possibly)

1. Metamask did not pop up when going to pools.spartanprotocol.org due to last network used not being BSC Mainnet
      -  Upon investigation realised it was because I had it set to Ethereum network, not BSC Mainnet
      -  Changed to BSC Mainnet manually
 
2. Change of network to BSC Mainnet after logging into Metamask did not resolve the issue of the pools page.
      -  Refreshed using the button on the right hand side of the pools page
      -  The normal pools values did not populate
      -  Needed to restart my browser for Metamask log-in popup to present and then see/access the pools information

Using Desktop, Chrome, Windows 10

**Comment by SamusElderg** [comment]
I reallllllllly appreciate the time you have taken to make this issue well-formatted and researched!
Whilst this was always kind of on my list; it never made it to the top of the priority list before work started on DAppV2. Thanks a million for your well created GitHub issue though we need more of this! Ill note though that these have already been addressed in DAppV2 and your suggestions there will be very beneficial once it is live and useable. I'll give a quick comment on each issue and how they have been addressed in DAppV2:

**Network Detection / Selection**
In DAppV2 (if using meta mask) the meta mask window will pop up when you visit the DApp if your network is not mainnet BSC, one click of the button in the modal that pops up will change it to the correct network.
Also if you click on the wallet and go to connect your wallet and switch from mainnet to testnet or vice versa the modal will also pop up then too

**Pool / Wallet / Asset Arrays Update on Network Change**
In DAppV2 the arrays of data refresh automatically if you change network or wallet 👍 
No need to refresh your browser; this will likely have some bugs on launch though so more hands on deck with testing it then would be great!
