### ISSUE TITLE
Clear the <Input> value on button-press

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#80]
When you click one of the buttons (25%, 50% etc) we need it to clear the current input value

Ideally if we can have the buttons change the input value instead of the input placeholder this will solve the issue

![image](https://user-images.githubusercontent.com/26967164/95680425-2aac2e00-0c0c-11eb-8406-de12161d2149.png)

**Comment by f1ntch** [comment]
Fixed with update of #newui join seems to work now.
