### ISSUE TITLE
FIX: Fonts not fully responsive in the cards 

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#87]
Let's maybe change the fonts to 'em' sizes so that they scale with the screen width?

Or just go through each page and make sure the cols break down as required at each screen width 

![IMG_20201012_185745_437.jpg](https://user-images.githubusercontent.com/26967164/95739738-e4170c00-0cbd-11eb-8a68-c94bfa0aafc0.jpg)

**Comment by f1ntch** [comment]
Fixed added also more width for the wiget display
![image](https://user-images.githubusercontent.com/12197739/95745968-5247d880-0c96-11eb-89aa-d9cb03421285.png)
