### ISSUE TITLE
FIX: On mobile, have the navmenu default to hidden

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#90]
Add a check for 'if mobile device' (screen width below a certain amount)

If below the threshold then `setNavIsOpen(false)`

Make sure it doesnt check forever; just once maybe `onPageLoad`?

**Comment by f1ntch** [comment]
Done

**Comment by SamusElderg** [comment]
Re-opening issue; not solved yet
