### ISSUE TITLE
FAQ PAGE: Changes

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/spartanpools-dapp#93]
Fix anonymous spelling mistake

Thorchain -> THORchain

developers spelling mistake

fix link on FAQ support page too (routes incorrectly)

**Comment by DnJoey** [comment]
![sd](https://user-images.githubusercontent.com/72745673/95780935-21cf6100-0ccd-11eb-8361-d093b5b90294.png)


it redirect to here  ;  https://pools.spartanprotocol.org/t.me/SpartanProtocolOrg
